# Generated by Django 3.1.5 on 2021-01-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Посты', 'verbose_name_plural': 'Блог'},
        ),
    ]
